[versions]
kotlin = "[2.3,3.0)"
ktlint = "[14.0,15.0)"
shadow = "[9.3,10.0)"
jreleaser = "[1.21,2.0)"
kotlinTimeJacksonModule = "1.0.1-SNAPSHOT"
kotlinxDatetimeJacksonModule = "1.0.1-SNAPSHOT"
jackson = "[2.20,3.0)"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
jreleaser = { id = "org.jreleaser", version.ref = "jreleaser" }

[libraries]
kotlin-test-junit5 = { group = "org.jetbrains.kotlin", name = "kotlin-test-junit5", version.ref = "kotlin" }

kotlin-time-jackson-module = { group = "com.zmkn.jackson", name = "kotlin-time-jackson-module", version.ref = "kotlinTimeJacksonModule" }
kotlinx-datetime-jackson-module = { group = "com.zmkn.jackson", name = "kotlinx-datetime-jackson-module", version.ref = "kotlinxDatetimeJacksonModule" }
jackson-databind = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "jackson" }
jackson-module-kotlin = { group = "com.fasterxml.jackson.module", name = "jackson-module-kotlin", version.ref = "jackson" }
