[versions]
kotlin = "[2.3,3.0)"
ktlint = "[14.0,15.0)"
shadow = "[9.3,10.0)"
jreleaser = "[1.23,2.0)"
kotlinTimeJacksonModule = "2.0.0-SNAPSHOT"
kotlinxDatetimeJacksonModule = "2.0.0-SNAPSHOT"
toolsJacksonBom = "[3.0,4.0)"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
jreleaser = { id = "org.jreleaser", version.ref = "jreleaser" }

[libraries]
kotlin-test-junit5 = { group = "org.jetbrains.kotlin", name = "kotlin-test-junit5", version.ref = "kotlin" }

kotlin-time-jackson-module = { group = "com.zmkn.jackson", name = "kotlin-time-jackson-module", version.ref = "kotlinTimeJacksonModule" }
kotlinx-datetime-jackson-module = { group = "com.zmkn.jackson", name = "kotlinx-datetime-jackson-module", version.ref = "kotlinxDatetimeJacksonModule" }
tools-jackson-bom = { group = "tools.jackson", name = "jackson-bom", version.ref = "toolsJacksonBom" }
tools-jackson-databind = { group = "tools.jackson.core", name = "jackson-databind" }
tools-jackson-module-kotlin = { group = "tools.jackson.module", name = "jackson-module-kotlin" }
